// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwUCChxmlw39Gd2C2outRj0W4ZOoWJ8pE',
    appId: '1:84600239657:web:2b0b126ceb5d8e2c84ce38',
    messagingSenderId: '84600239657',
    projectId: 'vav-management',
    authDomain: 'vav-management.firebaseapp.com',
    databaseURL: 'https://vav-management.firebaseio.com',
    storageBucket: 'vav-management.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXKYoL_qCSr1FYK3e-kozo5XSSIZaDGd0',
    appId: '1:84600239657:android:891cc718b5fade8084ce38',
    messagingSenderId: '84600239657',
    projectId: 'vav-management',
    databaseURL: 'https://vav-management.firebaseio.com',
    storageBucket: 'vav-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjcEYslluM8Si6CeZzeDQyBPGayoC1JWM',
    appId: '1:84600239657:ios:98b09fc6a997c22784ce38',
    messagingSenderId: '84600239657',
    projectId: 'vav-management',
    databaseURL: 'https://vav-management.firebaseio.com',
    storageBucket: 'vav-management.firebasestorage.app',
    iosClientId: '84600239657-ru9h0l74ohapq98jg54is7gc4dr6p3s1.apps.googleusercontent.com',
    iosBundleId: 'com.finscalc.finscalc',
  );
}
